# Generated by Django 5.1.4 on 2024-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
