# Generated by Django 5.1.4 on 2024-12-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
